
name: EKF Build Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  Linux-GCC:
    runs-on: ubuntu-latest
    container: px4io/px4-dev-base-focal:2021-05-04
    steps:
    - uses: actions/checkout@v1
    - name: main build
      run: cd ${GITHUB_WORKSPACE}/src/lib/ecl && make
    - name: clean build
      run: cd ${GITHUB_WORKSPACE}/src/lib/ecl && make clean
    - name: main test
      run: cd ${GITHUB_WORKSPACE}/src/lib/ecl && make test
  Linux-Clang:
    runs-on: ubuntu-latest
    container: px4io/px4-dev-clang:2021-05-04
    env:
      CC: clang
      CXX: clang++
    steps:
      - uses: actions/checkout@v1
      - name: main build
        run: cd ${GITHUB_WORKSPACE}/src/lib/ecl && make
      - name: clean build
        run: cd ${GITHUB_WORKSPACE}/src/lib/ecl && make clean
      - name: main test
        run: cd ${GITHUB_WORKSPACE}/src/lib/ecl && make test
  Mac-OS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: main build
        run: cd ${GITHUB_WORKSPACE}/src/lib/ecl && make
      - name: clean build
        run: cd ${GITHUB_WORKSPACE}/src/lib/ecl && make clean
      - name: main test
        run: cd ${GITHUB_WORKSPACE}/src/lib/ecl && make test
